# Generated by Django 4.1 on 2022-08-15 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_website_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('fake_name', models.CharField(max_length=444)),
                ('slug', models.SlugField(max_length=444)),
                ('image', models.ImageField(blank=True, upload_to='profile_images')),
                ('age', models.IntegerField(blank=True, default=20)),
                ('body', models.TextField(blank=True)),
                ('users', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
