# Generated by Django 4.1 on 2022-08-16 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0002_profile_website_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_users_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_created=True, blank=True)),
                ('text_body', models.TextField(blank=True)),
                ('commenter_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.profile_website_users')),
                ('disliked_comment', models.ManyToManyField(blank=True, related_name='dislaike_user', to=settings.AUTH_USER_MODEL)),
                ('find_post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.kharid_khone_orginal')),
                ('liked_comment', models.ManyToManyField(blank=True, related_name='liked_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_created'],
            },
        ),
    ]
