# Generated by Django 4.1 on 2022-08-16 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_comment_users_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replay_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_comment', models.DateTimeField(auto_created=True)),
                ('text_replay', models.TextField(blank=True)),
                ('finder_commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.comment_users_post')),
                ('replayer_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.profile_website_users')),
            ],
            options={
                'ordering': ['-date_comment'],
            },
        ),
    ]
